### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by DjAnu** [elias123tre/bitwarden_find_duplicates#3]
Hi I ran the script however it opens up a browser that's blank

**Comment by elias123tre** [comment]
Could be because your browser is unable to fetch the required files. Could you attach the error that comes up if you open Inspect elements (CTRL+SHIFT+I) when on the page? I will update the script to use a web server instead of opening just the file in the near future so stay tuned if it turns out this is your problem.

**Comment by elias123tre** [comment]
I'm assuming it got fixed by #4, therefore closing.
